FROM ubuntu:22.04
RUN apt-get update && apt-get install -y python3.9 python3.9-pip
RUN python3.9 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"
COPY requirements.txt .
RUN pip3 install -r requirements.txt
COPY app.py .
CMD ["python3", "app.py"]